---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: config-demo-secret
  namespace: config-demo
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: individual-mysecret
    template:
      type: Opaque
  data:
  - secretKey: baz
      remoteRef:
        key: secret/data/global/mysecret/foo
  - secretKey: boz
      remoteRef:
        key: secret/data/global/mysecret/bar