---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: individual-secret
  namespace: config-demo
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: individual-mysecret
    template:
      type: Opaque
  data:
  - secretKey: baz
    remoteRef:
      key: secret/global/mysecret/foo
  - secretKey: boz
    remoteRef:
      key: secret/global/mysecret/bar