apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  {{- if .Values.acm }}
  {{- if .Values.acm.availabilityConfig }}
  availabilityConfig: {{ default "High" .Values.acm.availabilityConfig }}
  {{- end }}
  {{- end }}
